code --install-extension bmewburn.vscode-intelephense-client
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension EditorConfig.EditorConfig
code --install-extension EmadFanaian.adonisjs-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension fivethree.vscode-ionic-snippets
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension Hridoy.adonisjs-snippets
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension octref.vetur
code --install-extension peakchen90.vue-beautify
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension rocketseat.RocketseatReactJS
code --install-extension rocketseat.RocketseatReactNative
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension royaction.color-manager
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Zignd.html-css-class-completion
